# Generated by Django 2.1 on 2020-03-14 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarksheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=6)),
                ('sem', models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five'), ('six', 'Six'), ('seven', 'Seven'), ('eight', 'Eight')], max_length=6)),
            ],
            options={
                'verbose_name': 'Mark Sheet Info',
                'verbose_name_plural': 'Mark Sheet Information',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=9)),
                ('department', models.CharField(choices=[('civil', 'Civil Engineering'), ('cse', 'Computer Science and Engineering'), ('ece', 'Electronics and Communication Engineering'), ('eee', 'Electrical and Electronics Engineering'), ('eie', 'Electrical and Instrumentation Engineering'), ('ibt', 'Industrial Biotech Engineering'), ('it', 'Information Technology'), ('mech', 'Mechanical Engineering'), ('prod', 'Production Engineering')], max_length=6)),
                ('phone_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('year_Of_Study', models.CharField(choices=[('one', 'First'), ('two', 'Second'), ('three', 'Third'), ('four', 'Final')], max_length=5)),
                ('date_Added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='marksheetdata',
            name='reg_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentData.Student'),
        ),
    ]
