# Generated by Django 2.1 on 2020-03-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheetdata',
            name='serial',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
