# Generated by Django 2.1 on 2020-03-15 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentData', '0002_auto_20200314_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('department', models.CharField(choices=[('civil', 'Civil Engineering'), ('cse', 'Computer Science and Engineering'), ('ece', 'Electronics and Communication Engineering'), ('eee', 'Electrical and Electronics Engineering'), ('eie', 'Electrical and Instrumentation Engineering'), ('ibt', 'Industrial Biotech Engineering'), ('it', 'Information Technology'), ('mech', 'Mechanical Engineering'), ('prod', 'Production Engineering')], max_length=6)),
                ('register_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentData.Student')),
            ],
        ),
    ]
